# Generated by Django 3.0.7 on 2020-06-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'unit')},
            },
        ),
    ]
